version: '3'

services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    networks:
      - veza
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
    networks:
      - veza
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mydb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: ''
      # Password for root access
      MYSQL_ROOT_PASSWORD: ''
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    command: --sql_mode=""
    networks:
      - veza
# Names our volume
volumes:
  my-db:
networks:
  veza:
    external: false
    name: veza
    driver: bridge
